config/routes.rb
Rails.application.routes.draw do
  resources :wxlite_settings
  resources :orders, only: [:index, :show] do
    member do
      put 'confirm'
    end
  end

  resources :visitors
  mount Ckeditor::Engine => '/ckeditor'
  resources :products
  resources :catalogs
  devise_for :users
  root 'home#index'
  post 'get-upload-token', to: 'home#upload_token'
  post 'pay', to: 'wechat_callback#pay'
  mount RootAPI => '/'
  mount GrapeSwaggerRails::Engine => '/chunchun-docs'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/visitor.rb
# == Schema Information
#
# Table name: visitors
#
#  id         :integer          not null, primary key
#  uid        :string
#  nickname   :string
#  headshot   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Visitor < ApplicationRecord
  attr_accessor :session_key
  has_many :shopping_carts, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :address_books, dependent: :destroy
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  before_action :set_visitor, only: [:show, :edit, :update, :destroy]

  # GET /visitors
  # GET /visitors.json
  def index
    @visitors = Visitor.all
  end

  # GET /visitors/1
  # GET /visitors/1.json
  def show
  end

  # GET /visitors/new
  def new
    @visitor = Visitor.new
  end

  # GET /visitors/1/edit
  def edit
  end

  # POST /visitors
  # POST /visitors.json
  def create
    @visitor = Visitor.new(visitor_params)

    respond_to do |format|
      if @visitor.save
        format.html { redirect_to @visitor, notice: 'Visitor was successfully created.' }
        format.json { render :show, status: :created, location: @visitor }
      else
        format.html { render :new }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visitors/1
  # PATCH/PUT /visitors/1.json
  def update
    respond_to do |format|
      if @visitor.update(visitor_params)
        format.html { redirect_to @visitor, notice: 'Visitor was successfully updated.' }
        format.json { render :show, status: :ok, location: @visitor }
      else
        format.html { render :edit }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visitors/1
  # DELETE /visitors/1.json
  def destroy
    @visitor.destroy
    respond_to do |format|
      format.html { redirect_to visitors_url, notice: 'Visitor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_visitor
      @visitor = Visitor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visitor_params
      params.require(:visitor).permit(:uid, :nickname, :headshot)
    end
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/visitors/_form.html.erb
<%= simple_form_for(@visitor) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :uid %>
    <%= f.input :nickname %>
    <%= f.input :headshot %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/visitors/edit.html.erb
<h1>Editing Visitor</h1>

<%= render 'form', visitor: @visitor %>

<%= link_to 'Show', @visitor %> |
<%= link_to 'Back', visitors_path %>

app/views/visitors/index.html.erb
<p id="notice"><%= notice %></p>

<h3>会员管理</h3>
<div class="row">
<% @visitors.each do |visitor| %>
  <div class="col-md-2">
    <a class="card" href="<%= visitor_path(visitor) %>">
      <h5 class="card-header"><%= visitor.nickname%></h5>
      <img style="height: 80px; width: 100%; display: block;" src="<%= visitor.headshot %>" alt="Card image">
    </a>
  </div>
  <% end %>
</div>

<br>

app/views/visitors/new.html.erb
<h1>New Visitor</h1>

<%= render 'form', visitor: @visitor %>

<%= link_to 'Back', visitors_path %>

app/views/visitors/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <%= image_tag @visitor.headshot, height: '80px', width: '80px', class: 'rounded-circle' %>
  <span><%= @visitor.nickname %>的订单</span>
</p>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">订单号</th>
      <th scope="col">订单价格</th>
      <th scope="col">订单状态</th>
      <th scope="col">收货地址</th>
    </tr>
  </thead>
  <tbody>
    <% @visitor.orders.each do |order|%>
      <tr>
        <th><%= link_to order.code, order_path(order) %></th>
        <td><%= order.price/100.0 %></td>
        <td><%= Order::STATUS[order.status.to_sym]%></td>
        <td><%= order.delivery_address%></td>
      </tr>
      <% end %>
  </tbody>
</table>