config/routes.rb
Rails.application.routes.draw do
  resources :wxlite_settings
  resources :orders, only: [:index, :show] do
    member do
      put 'confirm'
    end
  end

  resources :visitors
  mount Ckeditor::Engine => '/ckeditor'
  resources :products
  resources :catalogs
  devise_for :users
  root 'home#index'
  post 'get-upload-token', to: 'home#upload_token'
  post 'pay', to: 'wechat_callback#pay'
  mount RootAPI => '/'
  mount GrapeSwaggerRails::Engine => '/chunchun-docs'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id         :integer          not null, primary key
#  visitor_id :integer
#  code       :string
#  price      :integer
#  status     :string
#  features   :jsonb
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_orders_on_visitor_id  (visitor_id)
#
# Foreign Keys
#
#  fk_rails_...  (visitor_id => visitors.id)
#

class Order < ApplicationRecord
  belongs_to :visitor
  has_many :order_products, dependent: :destroy
  has_many :products, through: :order_products
  store_accessor :features, :delivery_username, :delivery_phone, :delivery_address, :pay_time
  after_create :generate_code

  STATUS = {
    open: '未支付', #订单结算
    pending: '支付中',
    paid: '支付成功',
    deliveried: '已发货',
    completed: '完成',
    cancelled: '已取消'
  }


  after_initialize do
    self.status ||= 'open'
  end

  def generate_code
    today = Time.now.beginning_of_day
    todayFirstOrder = self.class.where("? <= created_at", today).order(created_at: :asc).first
    number = todayFirstOrder && self.id - todayFirstOrder.id + 1 || 1
    raise '订单当日数量超出系统限制' if number.to_s.length > 5
    self.update(code: "#{today.strftime('%Y%m%d')}#{number.to_s.rjust(5, '0')}")
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy, :confirm]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all.order('updated_at DESC').page(params[:page])
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def confirm
    @order.status = 'deliveried'
    @order.save!
    redirect_to order_url(@order)
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end
end

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h3>
  订单列表
</h3>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">订单号</th>
      <th scope="col">价格(元)</th>
      <th scope="col">状态</th>
      <th scope="col">创建时间</th>
      <th scope="col">付款时间</th>
      <th scope="col">客户</th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order|%>
    <tr>
      <td><%= link_to order.code, order_path(order) %></td>
      <td><%= order.price/100.0 %></td>
      <td><%= Order::STATUS[order.status.to_sym] %></td>
      <td><%= order.created_at.localtime %></td>
      <td><%= order.pay_time %></td>
      <td><%= order.visitor.nickname %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>
<h5>
  <%= @order.code %><span class="badge badge-danger"><%= Order::STATUS[@order.status.to_sym] %></span>
  <%= link_to '确认发货', confirm_order_path(@order), method: :put, class: 'btn btn-danger' if @order.status == 'paid' %>
  <%= link_to '返回', orders_path, class: 'btn btn-warning' %>
</h5>
<div class='row mt-5'>
  <div class='col'>价格: <%= @order.price.to_i/100.0 %>元</div>
  <div class='col'>收货人: <%= @order.delivery_username %></div>
  <div class='col'>收货地址: <%= @order.delivery_address %></div>
  <div class='col'>联系电话: <%= @order.delivery_phone %></div>
</div>
<div class='row mt-5 ml-1'>
  <p>购买产品:</p>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">产品图片</th>
        <th scope="col">产品名称</th>
        <th scope="col">产品价格</th>
        <th scope="col">购买数量</th>
      </tr>
    </thead>
    <tbody>
      <% @order.order_products.each do |order_product|%>
        <tr>
          <th><%= image_tag order_product.product.first_image, width: '100px'%></th>
          <td><%= link_to order_product.product.name, product_path(order_product.product) %></td>
          <td><%= order_product.product.sell_price/100.0%></td>
          <td><%= order_product.amount%></td>
        </tr>
       <% end %>
    </tbody>
  </table>
</div>