config/routes.rb
Rails.application.routes.draw do
  resources :wxlite_settings
  resources :orders, only: [:index, :show] do
    member do
      put 'confirm'
    end
  end

  resources :visitors
  mount Ckeditor::Engine => '/ckeditor'
  resources :products
  resources :catalogs
  devise_for :users
  root 'home#index'
  post 'get-upload-token', to: 'home#upload_token'
  post 'pay', to: 'wechat_callback#pay'
  mount RootAPI => '/'
  mount GrapeSwaggerRails::Engine => '/chunchun-docs'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  name        :string
#  price       :string
#  images      :string           is an Array
#  description :string
#  content     :text
#  features    :jsonb
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  catalog_id  :integer
#  is_deleted  :boolean          default(FALSE)
#
# Indexes
#
#  index_products_on_catalog_id  (catalog_id)
#
# Foreign Keys
#
#  fk_rails_...  (catalog_id => catalogs.id)
#

class Product < ApplicationRecord
  has_many :product_dimensions
  belongs_to :catalog
  acts_as_taggable
  store_accessor :features, :sell_price, :stock
  validates_presence_of :price, :sell_price, :name, :stock

  def first_image
    images ? images.first : 'http://p64xi7w31.bkt.clouddn.com/WechatIMG602.jpeg'
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.where(is_deleted: false).order('updated_at DESC').page(params[:page])
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    set_product_price
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    set_product_price
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    # @product.destroy
    @product.update(is_deleted: true)
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :images, :description, :stock, :sell_price, :content, :tag_list, :catalog_id,
                                      images: [])
    end

    def set_product_price
      params[:product][:price] = params[:product][:price].to_f * 100
      params[:product][:sell_price] = params[:product][:sell_price].to_f * 100
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-4">
      <%= form.label :name %>
      <%= form.text_field :name, id: :product_name, class: 'form-control' %>
    </div>

    <div class="col-md-4">
      <%= form.label :price %>
      <%= form.text_field :price, value: product.new_record? ? '' : product.price.to_i/100.0, id: :product_price, class: 'form-control' %>
    </div>
    <div class="col-md-4">
      <%= form.label :sell_price %>
      <%= form.text_field :sell_price, value: product.new_record? ? '' : product.sell_price.to_i/100.0, id: :product_sell_price, class: 'form-control' %>
    </div>
  </div>
  <div class="row mt-2">
    <div class="col-md-4">
      <%= form.label :stock %>
      <%= form.text_field :stock, id: :product_stock, class: 'form-control' %>
    </div> 
    <div class="col-md-4">
      <%= form.label :catalog %>
      <div rel="vca" role="cascader" name="product[catalog_id]" value="<%= @product.catalog_id %>"  props='{"label": "name", "value": "id", "children": "children_data"}' url="http://localhost:3000/catalogs.json"></div>
    </div> 
    <div class="col-md-4">
      <%= form.label :tag %>
      <div rel="vca" role="tag" name="product[tag_list]" value="<%= @product.tag_list %>" type="success" closable disable-transitions hit size="medium"></div>
    </div>
  </div>
  <div class="row mt-3 ml-1">
    <%= form.label :images %>
    <p rel="vca" role="image-upload"
        name="product[images][]"
        token-url="http://localhost:3000/get-upload-token"
        upload-url="//up-z2.qiniup.com"
        domain="<%= ENV['QINIU_DOMAIN'] %>"
        file-list="<%= @product.images.join(',') if @product.images %>"
        multiple
        list-type="picture-card"
        limit="5" 
        tip="最多上传5个图片"></p>
  </div>
  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :product_description, class: 'form-control' %>
  </div>
  <div class="field">
    <%= form.label :content %>
    <%= form.cktext_area :content, id: :product_content, class: 'form-control', cols: 40, ckeditor: { toolbar: 'mini' } %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-lg btn-success btn-block' %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h3>
  产品编辑
  <p class="text-right">
    <%= link_to '查看', @product, class: 'btn btn-success' %> |
    <%= link_to '返回', products_path, class: 'btn btn-warning'  %>
  </p>
</h3>

<%= render 'form', product: @product %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h3>
  产品列表
  <%= link_to '新建产品', new_product_path, class: 'btn btn-success' %>
</h3>
<div class="row">
  <% @products.each do |product| %>
  <div class="col-md-3">
    <div class="card">
      <p class="card-header"><%= product.name%></p>
      <div class="card-body">
        <div class="row">
          <div class="col-6 text-left">
            <h5 class="card-title text-danger"><%= product.sell_price.to_i/100.0 %>元</h5>
          </div>
          <div class="col-6 text-right">
            <h5 class="card-title"><h6 class="card-subtitle text-muted"><span class="badge badge-danger"><%= product.catalog.full_name %></span></h6></h5>
          </div>
        </div>
      </div>
      <img style="height: 150px; width: 100%; display: block;" src="<%= product.first_image %>" alt="Card image">
      <div class="card-body">
        <p class="card-text"><%= product.description.truncate(30) %></p>
        <% product.tags.each do |tag|%>
          <span class="badge badge-success"><%= tag.name%></span>
        <% end%>
      </div>
      <div class="card-body">
        <%= link_to '查看', product_path(product), class: 'btn btn-sm btn-success' %>
        <%= link_to '编辑', edit_product_path(product), class: 'btn btn-sm btn-warning' %>
        <%= link_to '删除', product, method: :delete, data: { confirm: '确定要删除吗?' }, class: 'btn btn-sm btn-danger' %>
      </div>
    </div>
  </div>
  <% end %>
</div>
<br>

app/views/products/new.html.erb
<h3>
  新建产品
  <p class="text-right">
    <%= link_to '返回', products_path, class: 'btn btn-warning'  %>
  </p>
</h3>

<%= render 'form', product: @product %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<h5>
  <%= @product.name %><span class="badge badge-danger"><%= @product.catalog.full_name %></span>
  <%= link_to '编辑', edit_product_path(@product), class: 'btn btn-success' %>
  <%= link_to '返回', products_path, class: 'btn btn-warning' %>
</h5>
<div class='row mt-5'>
  <div class='col'>价格: <%= @product.price.to_i/100.0 %>元</div>
  <div class='col'>卖价: <%= @product.sell_price.to_i/100.0 %>元</div>
  <div class='col'>库存: <%= @product.stock %></div>
  <div class='col'>标签: 
    <% @product.tags.each do |tag|%>
      <span class="badge badge-success"><%= tag.name%></span>
    <% end %>
  </div>
</div>
<div class='row mt-5 ml-1'>
  <p>产品简介: <%= @product.description %></p>
</div>
<div class='row mt-5 ml-1'>
  <p>产品图片:</p>
  <% @product.images.each do |image|%>
    <img src="<%= image %>" class="rounded float-right ml-5" alt="产品图片" style="height: 200px;">
  <% end %>
</div>
<div class="mt-5">
  <h5>产品详情</h5>
  <%= raw(@product.content)%>
</div>