config/routes.rb
Rails.application.routes.draw do
  resources :wxlite_settings
  resources :orders, only: [:index, :show] do
    member do
      put 'confirm'
    end
  end

  resources :visitors
  mount Ckeditor::Engine => '/ckeditor'
  resources :products
  resources :catalogs
  devise_for :users
  root 'home#index'
  post 'get-upload-token', to: 'home#upload_token'
  post 'pay', to: 'wechat_callback#pay'
  mount RootAPI => '/'
  mount GrapeSwaggerRails::Engine => '/chunchun-docs'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="#">纯纯饰品</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <%= 'active' if controller_name == 'orders' %>">
        <a class="nav-link" href="<%= orders_path %>">订单</a>
      </li>
      <li class="nav-item <%= 'active' if controller_name == 'products' %>">
        <a class="nav-link" href="<%= products_path %>">产品</a>
      </li>
      <li class="nav-item <%= 'active' if controller_name == 'catalogs' %>">
        <a class="nav-link" href="<%= catalogs_path %>">产品分类</a>
      </li>
      <li class="nav-item <%= 'active' if controller_name == 'visitors' %>">
        <a class="nav-link" href="<%= visitors_path %>">客户</a>
      </li>
      <li class="nav-item <%= 'active' if controller_name == 'wxlite_settings' %>">
        <a class="nav-link" href="<%= wxlite_settings_path %>">小程序设置</a>
      </li>
    </ul>
    <span class="text-success"><%= current_user.email%></span>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>纯纯</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'hello_vue' %>
    <%= stylesheet_pack_tag 'hello_vue' %>
  </head>

  <body>
    <%= render 'layouts/header' if user_signed_in? %>
    <div class="content">
      <%= yield %>
    </div>
  </body>
</html>